### ISSUE TITLE
Maybe a typo in the paper

### ISSUE THREAD

**Issue by SivilTaram** [xwhan/Knowledge-Aware-Reader#4]
Hi guys, thank you for open-sourcing the code! However, from the provided arxiv URL, I find one thing which may be a typo. Please see the red block in the following screenshot:

![image](https://user-images.githubusercontent.com/10275209/62106283-74467c80-b2d7-11e9-95f6-d8621ac607ad.png)

I cannot see any line which mentions about `28.1` on F1, but it appears in the ablation study table. Therefore, I guess the result in table 1 should be `28.1`, right? The same for `Hits@1`. Thanks :)

**Comment by xwhan** [comment]
Hi, that's the difference between dev and test performance.
