### ISSUE TITLE
How to find the topic entities mentioned by the question?

### ISSUE THREAD

**Issue by Frankszc** [xwhan/Knowledge-Aware-Reader#8]
Hello, thanks a lot for the code first! I have an question : I find there is a sign(2) about the top entities mentioned by the question, I can find this paper "Semantic Parsing for Single-Relation Question Answering" by the sign, but I can't find the method how to determine the topic entities.
I would really appreciate if you can help me when you aren't busy, thanks a lot!

**Comment by xwhan** [comment]
hi @Frankszc, research on WebQSP usually just reused the topic entities recognized by S-MART/STAGG. Unfortunately, their source code is not open sourced. Existing available entity linking tools include TagMe and Google Cloud NLP API.

**Comment by Frankszc** [comment]
> hi @Frankszc, research on WebQSP usually just reused the topic entities recognized by S-MART/STAGG. Unfortunately, their source code is not open sourced. Existing available entity linking tools include TagMe and Google Cloud NLP API.

ok，thanks a lot!
